In [135]:
import pandas as pd
import numpy as np

In [136]:
df=pd.read_csv(r"D:\Codex Ai Course\Sessions\Data Sets\Store.csv")
df

,Order_ID,Product_Name,Category,Store,City,Unit_Price,Quantity,Discount (%),Stock,Rating,Payment_Method,Customer_Gender,Order_Date
0,10001,Chair,Networking,Online Market,Tanta,1824.0,1.0,10.0,44.0,2.5,Credit Card,Male,2025-04-21
1,10002,Webcam,Networking,Digital World,Giza,10701.0,2.0,10.0,263.0,4.5,Debit Card,Male,2024-04-23
2,10003,USB Cable,Furniture,Computer House,Alexandria,985.0,6.0,20.0,NaN,1.6,Debit Card,Female,2024-01-20
3,10004,Headphones,Networking,Mega Store,Ismailia,13445.0,2.0,10.0,102.0,1.6,Vodafone Cash,Female,2025-06-11
4,10005,NaN,Electronics,Computer House,Luxor,29858.0,NaN,25.0,124.0,2.3,Credit Card,Male,2024-05-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,10796,Phone,Networking,Digital World,Cairo,5989.0,3.0,30.0,NaN,4.2,Debit Card,Male,2024-01-16
796,10797,Printer,Networking,NaN,Mansoura,14746.0,3.0,10.0,295.0,2.4,Cash,Male,2024-11-29
797,10798,Monitor,Furniture,Smart Shop,Alexandria,14844.0,1.0,30.0,150.0,3.8,Cash,Female,2025-04-08
798,10799,Desk,Furniture,NaN,Tanta,2345.0,3.0,0.0,156.0,1.8,Debit Card,Male,2024-02-28
799,10800,Keyboard,Networking,Smart Shop,Giza,22119.0,4.0,30.0,205.0,4.0,Instapay,Female,2024-06-25

In [137]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         800 non-null    int64
 1   Product_Name     720 non-null    str
 2   Category         720 non-null    str
 3   Store            720 non-null    str
 4   City             720 non-null    str
 5   Unit_Price       720 non-null    float64
 6   Quantity         720 non-null    float64
 7   Discount (%)     720 non-null    float64
 8   Stock            720 non-null    float64
 9   Rating           720 non-null    float64
 10  Payment_Method   720 non-null    str
 11  Customer_Gender  720 non-null    str
 12  Order_Date       800 non-null    str
dtypes: float64(5), int64(1), str(7)
memory usage: 81.4 KB

In [138]:
df.isna().sum()

Order_ID            0
Product_Name       80
Category           80
Store              80
City               80
Unit_Price         80
Quantity           80
Discount (%)       80
Stock              80
Rating             80
Payment_Method     80
Customer_Gender    80
Order_Date          0
dtype: int64

In [139]:
df["Order_Date"]=pd.to_datetime(df["Order_Date"])
df

,Order_ID,Product_Name,Category,Store,City,Unit_Price,Quantity,Discount (%),Stock,Rating,Payment_Method,Customer_Gender,Order_Date
0,10001,Chair,Networking,Online Market,Tanta,1824.0,1.0,10.0,44.0,2.5,Credit Card,Male,2025-04-21
1,10002,Webcam,Networking,Digital World,Giza,10701.0,2.0,10.0,263.0,4.5,Debit Card,Male,2024-04-23
2,10003,USB Cable,Furniture,Computer House,Alexandria,985.0,6.0,20.0,NaN,1.6,Debit Card,Female,2024-01-20
3,10004,Headphones,Networking,Mega Store,Ismailia,13445.0,2.0,10.0,102.0,1.6,Vodafone Cash,Female,2025-06-11
4,10005,NaN,Electronics,Computer House,Luxor,29858.0,NaN,25.0,124.0,2.3,Credit Card,Male,2024-05-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,10796,Phone,Networking,Digital World,Cairo,5989.0,3.0,30.0,NaN,4.2,Debit Card,Male,2024-01-16
796,10797,Printer,Networking,NaN,Mansoura,14746.0,3.0,10.0,295.0,2.4,Cash,Male,2024-11-29
797,10798,Monitor,Furniture,Smart Shop,Alexandria,14844.0,1.0,30.0,150.0,3.8,Cash,Female,2025-04-08
798,10799,Desk,Furniture,NaN,Tanta,2345.0,3.0,0.0,156.0,1.8,Debit Card,Male,2024-02-28
799,10800,Keyboard,Networking,Smart Shop,Giza,22119.0,4.0,30.0,205.0,4.0,Instapay,Female,2024-06-25

In [140]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         800 non-null    int64
 1   Product_Name     720 non-null    str
 2   Category         720 non-null    str
 3   Store            720 non-null    str
 4   City             720 non-null    str
 5   Unit_Price       720 non-null    float64
 6   Quantity         720 non-null    float64
 7   Discount (%)     720 non-null    float64
 8   Stock            720 non-null    float64
 9   Rating           720 non-null    float64
 10  Payment_Method   720 non-null    str
 11  Customer_Gender  720 non-null    str
 12  Order_Date       800 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(5), int64(1), str(6)
memory usage: 81.4 KB

In [141]:
df.describe(include="O")

C:\Users\dell\AppData\Local\Temp\ipykernel_20240\504318277.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="O")

,Product_Name,Category,Store,City,Payment_Method,Customer_Gender
count,720,720,720,720,720,720
unique,20,5,8,10,5,2
top,Printer,Electronics,Digital World,Tanta,Credit Card,Female
freq,47,151,106,85,170,365

In [142]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         800 non-null    int64
 1   Product_Name     720 non-null    str
 2   Category         720 non-null    str
 3   Store            720 non-null    str
 4   City             720 non-null    str
 5   Unit_Price       720 non-null    float64
 6   Quantity         720 non-null    float64
 7   Discount (%)     720 non-null    float64
 8   Stock            720 non-null    float64
 9   Rating           720 non-null    float64
 10  Payment_Method   720 non-null    str
 11  Customer_Gender  720 non-null    str
 12  Order_Date       800 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(5), int64(1), str(6)
memory usage: 81.4 KB

In [143]:
df= df.fillna( {
    "Product_Name":"Unknown",
    "Category":"Unknown",
    "Store": "Unknown",
    "City": "Unknown",
    "Unit_Price" :df["Unit_Price"].mean(),
    "Quantity" :df["Quantity"].mean(),
    "Discount (%)":df["Discount (%)"].mean(),
    "Stock":df["Stock"].mean(),
    "Rating":df["Rating"].median(),
    "Payment_Method" :"Unknown",
    "Customer_Gender":"Unknown"



    
    
     



} )

In [144]:
df

,Order_ID,Product_Name,Category,Store,City,Unit_Price,Quantity,Discount (%),Stock,Rating,Payment_Method,Customer_Gender,Order_Date
0,10001,Chair,Networking,Online Market,Tanta,1824.0,1.000000,10.0,44.000000,2.5,Credit Card,Male,2025-04-21
1,10002,Webcam,Networking,Digital World,Giza,10701.0,2.000000,10.0,263.000000,4.5,Debit Card,Male,2024-04-23
2,10003,USB Cable,Furniture,Computer House,Alexandria,985.0,6.000000,20.0,149.238889,1.6,Debit Card,Female,2024-01-20
3,10004,Headphones,Networking,Mega Store,Ismailia,13445.0,2.000000,10.0,102.000000,1.6,Vodafone Cash,Female,2025-06-11
4,10005,Unknown,Electronics,Computer House,Luxor,29858.0,5.465278,25.0,124.000000,2.3,Credit Card,Male,2024-05-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,10796,Phone,Networking,Digital World,Cairo,5989.0,3.000000,30.0,149.238889,4.2,Debit Card,Male,2024-01-16
796,10797,Printer,Networking,Unknown,Mansoura,14746.0,3.000000,10.0,295.000000,2.4,Cash,Male,2024-11-29
797,10798,Monitor,Furniture,Smart Shop,Alexandria,14844.0,1.000000,30.0,150.000000,3.8,Cash,Female,2025-04-08
798,10799,Desk,Furniture,Unknown,Tanta,2345.0,3.000000,0.0,156.000000,1.8,Debit Card,Male,2024-02-28
799,10800,Keyboard,Networking,Smart Shop,Giza,22119.0,4.000000,30.0,205.000000,4.0,Instapay,Female,2024-06-25

In [145]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         800 non-null    int64
 1   Product_Name     800 non-null    str
 2   Category         800 non-null    str
 3   Store            800 non-null    str
 4   City             800 non-null    str
 5   Unit_Price       800 non-null    float64
 6   Quantity         800 non-null    float64
 7   Discount (%)     800 non-null    float64
 8   Stock            800 non-null    float64
 9   Rating           800 non-null    float64
 10  Payment_Method   800 non-null    str
 11  Customer_Gender  800 non-null    str
 12  Order_Date       800 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(5), int64(1), str(6)
memory usage: 81.4 KB

In [146]:
df.isna().sum()

Order_ID           0
Product_Name       0
Category           0
Store              0
City               0
Unit_Price         0
Quantity           0
Discount (%)       0
Stock              0
Rating             0
Payment_Method     0
Customer_Gender    0
Order_Date         0
dtype: int64

In [147]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
795    False
796    False
797    False
798    False
799    False
Length: 800, dtype: bool

In [148]:
df.duplicated().sum()

np.int64(0)

In [149]:
df.describe()

,Order_ID,Unit_Price,Quantity,Discount (%),Stock,Rating,Order_Date
count,800.0000,800.000000,800.000000,800.000000,800.000000,800.000000,800
mean,10400.5000,15200.405556,5.465278,15.673611,149.238889,2.993750,2025-01-08 10:19:12
min,10001.0000,75.000000,1.000000,0.000000,0.000000,1.000000,2024-01-01 00:00:00
25%,10200.7500,8622.500000,3.000000,10.000000,85.000000,2.100000,2024-06-28 12:00:00
50%,10400.5000,15200.405556,5.465278,15.673611,149.238889,3.000000,2025-01-10 12:00:00
75%,10600.2500,21843.000000,8.000000,25.000000,215.250000,3.900000,2025-07-13 00:00:00
max,10800.0000,29858.000000,10.000000,30.000000,299.000000,5.000000,2025-12-30 00:00:00
std,231.0844,8177.508077,2.752887,9.630098,83.314586,1.103929,NaN

In [150]:
df.describe(include="O")

C:\Users\dell\AppData\Local\Temp\ipykernel_20240\504318277.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="O")

,Product_Name,Category,Store,City,Payment_Method,Customer_Gender
count,800,800,800,800,800,800
unique,21,6,9,11,6,3
top,Unknown,Electronics,Digital World,Tanta,Credit Card,Female
freq,80,151,106,85,170,365

In [151]:
df["Product_Name"].value_counts()

Product_Name
Unknown        80
Printer        47
Mouse          45
Laptop         42
Hard Drive     42
SSD            42
USB Cable      40
Speaker        40
Microphone     39
Chair          35
Phone          35
Smart Watch    35
Monitor        34
Tablet         34
Webcam         33
Keyboard       32
Desk           32
Camera         31
Power Bank     28
Headphones     27
Router         27
Name: count, dtype: int64

In [152]:
list(df["Product_Name"].unique())

['Chair',
 'Webcam',
 'USB Cable',
 'Headphones',
 'Unknown',
 'Microphone',
 'Monitor',
 'Phone',
 'Mouse',
 'Keyboard',
 'Speaker',
 'Desk',
 'Laptop',
 'Hard Drive',
 'Camera',
 'SSD',
 'Printer',
 'Tablet',
 'Router',
 'Power Bank',
 'Smart Watch']

In [153]:
df

,Order_ID,Product_Name,Category,Store,City,Unit_Price,Quantity,Discount (%),Stock,Rating,Payment_Method,Customer_Gender,Order_Date
0,10001,Chair,Networking,Online Market,Tanta,1824.0,1.000000,10.0,44.000000,2.5,Credit Card,Male,2025-04-21
1,10002,Webcam,Networking,Digital World,Giza,10701.0,2.000000,10.0,263.000000,4.5,Debit Card,Male,2024-04-23
2,10003,USB Cable,Furniture,Computer House,Alexandria,985.0,6.000000,20.0,149.238889,1.6,Debit Card,Female,2024-01-20
3,10004,Headphones,Networking,Mega Store,Ismailia,13445.0,2.000000,10.0,102.000000,1.6,Vodafone Cash,Female,2025-06-11
4,10005,Unknown,Electronics,Computer House,Luxor,29858.0,5.465278,25.0,124.000000,2.3,Credit Card,Male,2024-05-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,10796,Phone,Networking,Digital World,Cairo,5989.0,3.000000,30.0,149.238889,4.2,Debit Card,Male,2024-01-16
796,10797,Printer,Networking,Unknown,Mansoura,14746.0,3.000000,10.0,295.000000,2.4,Cash,Male,2024-11-29
797,10798,Monitor,Furniture,Smart Shop,Alexandria,14844.0,1.000000,30.0,150.000000,3.8,Cash,Female,2025-04-08
798,10799,Desk,Furniture,Unknown,Tanta,2345.0,3.000000,0.0,156.000000,1.8,Debit Card,Male,2024-02-28
799,10800,Keyboard,Networking,Smart Shop,Giza,22119.0,4.000000,30.0,205.000000,4.0,Instapay,Female,2024-06-25

In [154]:
list(df["Category"].unique())

['Networking', 'Furniture', 'Electronics', 'Unknown', 'Accessories', 'Office']

In [155]:
list(df["Store"].unique())

['Online Market',
 'Digital World',
 'Computer House',
 'Mega Store',
 'Unknown',
 'Elite Store',
 'Smart Shop',
 'Tech Zone',
 'Future Electronics']

In [156]:
list(df["City"].unique())

['Tanta',
 'Giza',
 'Alexandria',
 'Ismailia',
 'Luxor',
 'Aswan',
 'Unknown',
 'Port Said',
 'Mansoura',
 'Suez',
 'Cairo']

In [157]:
list(df["Payment_Method"].unique())

['Credit Card', 'Debit Card', 'Vodafone Cash', 'Unknown', 'Cash', 'Instapay']

In [158]:
list(df["Customer_Gender"].unique())

['Male', 'Female', 'Unknown']

In [159]:
tolal_Revenue=df['Total_Sales'] = df['Unit_Price'] * df['Quantity'] * (1 - df['Discount (%)']/100)
tolal_Revenue

0        1641.600000
1       19261.800000
2        4728.000000
3       24201.000000
4      122386.697917
           ...
795     12576.900000
796     39814.200000
797     10390.800000
798      7035.000000
799     61933.200000
Length: 800, dtype: float64

In [160]:
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month
print(df[['Total_Sales','Year','Month']].head(10))

     Total_Sales  Year  Month
0    1641.600000  2025      4
1   19261.800000  2024      4
2    4728.000000  2024      1
3   24201.000000  2025      6
4  122386.697917  2024      5
5   17361.000000  2024      7
6   62868.750000  2025      6
7   49102.200000  2025      1
8  124215.600000  2025      5
9   91852.800000  2024      6

**Which category generates the most revenue?**

In [161]:
print(df.groupby('Category')['Total_Sales'].sum().sort_values(ascending=False))

Category
Electronics    1.128999e+07
Office         1.115272e+07
Furniture      9.909402e+06
Accessories    9.683172e+06
Networking     8.555617e+06
Unknown        5.858916e+06
Name: Total_Sales, dtype: float64

**What is the best-selling product in terms of volume?**

In [162]:
print(df.groupby('Product_Name')['Quantity'].sum().sort_values(ascending=False))

Product_Name
Unknown        376.722222
Mouse          262.395833
Printer        260.395833
USB Cable      233.930556
Microphone     232.791667
Laptop         232.256944
Speaker        225.861111
Chair          211.791667
Smart Watch    209.256944
Hard Drive     205.930556
Tablet         195.930556
Webcam         192.395833
Monitor        189.000000
Phone          185.395833
SSD            182.465278
Desk           176.861111
Keyboard       172.930556
Router         164.326389
Headphones     155.326389
Camera         154.395833
Power Bank     151.861111
Name: Quantity, dtype: float64

**Which city is the most expensive?**

In [163]:
print(df.groupby('City')['Total_Sales'].sum().sort_values(ascending=False))

City
Unknown       6.220732e+06
Luxor         5.981264e+06
Tanta         5.709231e+06
Mansoura      5.597422e+06
Aswan         5.439242e+06
Suez          5.286350e+06
Giza          5.285413e+06
Ismailia      4.663468e+06
Cairo         4.336042e+06
Port Said     4.011898e+06
Alexandria    3.918753e+06
Name: Total_Sales, dtype: float64

In [164]:
print(df.groupby('Category')[['Unit_Price', 'Quantity']].mean())

               Unit_Price  Quantity
Category
Accessories  14910.383110  5.254428
Electronics  14779.832303  5.896523
Furniture    14119.101323  5.503732
Networking   15725.150347  4.887912
Office       16459.839157  5.627443
Unknown      15398.985833  5.603212

In [165]:
print(df.groupby('Product_Name')['Quantity'].sum().sort_values(ascending=False))

Product_Name
Unknown        376.722222
Mouse          262.395833
Printer        260.395833
USB Cable      233.930556
Microphone     232.791667
Laptop         232.256944
Speaker        225.861111
Chair          211.791667
Smart Watch    209.256944
Hard Drive     205.930556
Tablet         195.930556
Webcam         192.395833
Monitor        189.000000
Phone          185.395833
SSD            182.465278
Desk           176.861111
Keyboard       172.930556
Router         164.326389
Headphones     155.326389
Camera         154.395833
Power Bank     151.861111
Name: Quantity, dtype: float64

In [166]:
print(df['Product_Name'].mode()[0])
print(df['Product_Name'].value_counts())

Unknown
Product_Name
Unknown        80
Printer        47
Mouse          45
Laptop         42
Hard Drive     42
SSD            42
USB Cable      40
Speaker        40
Microphone     39
Chair          35
Phone          35
Smart Watch    35
Monitor        34
Tablet         34
Webcam         33
Keyboard       32
Desk           32
Camera         31
Power Bank     28
Headphones     27
Router         27
Name: count, dtype: int64

In [167]:
print(df.groupby('City')['Total_Sales'].sum().sort_values(ascending=False))

City
Unknown       6.220732e+06
Luxor         5.981264e+06
Tanta         5.709231e+06
Mansoura      5.597422e+06
Aswan         5.439242e+06
Suez          5.286350e+06
Giza          5.285413e+06
Ismailia      4.663468e+06
Cairo         4.336042e+06
Port Said     4.011898e+06
Alexandria    3.918753e+06
Name: Total_Sales, dtype: float64

In [168]:
print(df['City'].mode()[0])
print(df['City'].value_counts())

Tanta
City
Tanta         85
Giza          80
Unknown       80
Luxor         79
Mansoura      77
Aswan         75
Suez          68
Cairo         68
Port Said     67
Ismailia      63
Alexandria    58
Name: count, dtype: int64

In [169]:
df.describe(include="O")

C:\Users\dell\AppData\Local\Temp\ipykernel_20240\504318277.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="O")

,Product_Name,Category,Store,City,Payment_Method,Customer_Gender
count,800,800,800,800,800,800
unique,21,6,9,11,6,3
top,Unknown,Electronics,Digital World,Tanta,Credit Card,Female
freq,80,151,106,85,170,365

In [170]:
print(df.groupby('Payment_Method')['Rating'].mean().sort_values(ascending=False))

Payment_Method
Instapay         3.181618
Debit Card       3.086897
Cash             2.956429
Credit Card      2.925294
Vodafone Cash    2.900775
Unknown          2.866250
Name: Rating, dtype: float64

In [171]:
df["Product_Name"].value_counts()

Product_Name
Unknown        80
Printer        47
Mouse          45
Laptop         42
Hard Drive     42
SSD            42
USB Cable      40
Speaker        40
Microphone     39
Chair          35
Phone          35
Smart Watch    35
Monitor        34
Tablet         34
Webcam         33
Keyboard       32
Desk           32
Camera         31
Power Bank     28
Headphones     27
Router         27
Name: count, dtype: int64

In [172]:
df["Payment_Method"].value_counts()

Payment_Method
Credit Card      170
Debit Card       145
Cash             140
Instapay         136
Vodafone Cash    129
Unknown           80
Name: count, dtype: int64